#ifndef CARTDIR_H
#define CARTDIR_H

enum {
    /* 00 */ CART_ROOT_INDEXEDSET_GRAPHIC_OBJECTS = 0,
    /* 01 */ CART_ROOT_INDEXEDSET_INTELLIGENCE,
    /* 02 */ CART_ROOT_UNINDEXEDSET_OBJECT_TYPES,
    /* 03 */ CART_ROOT_INDEXEDSET_TEXTURE_SETS,
    /* 04 */ CART_ROOT_INDEXEDSET_PARTICLE_EFFECTS,
    /* 05 */ CART_ROOT_INDEXEDSET_LEVELS,
    /* 06 */ CART_ROOT_INDEXEDSET_LOAD_SAVE_PERSISTENT_DATA,
    /* 07 */ CART_ROOT_INDEXEDSET_GAME_PERSISTENT_DATA,
    /* 09 */ CART_ROOT_INDEXEDSET_BINARIES = 9,
    /* 10 */ CART_ROOT_UNINDEXEDSET_BINARY_TYPES,
    /* 11 */ CART_ROOT_INDEXEDSET_PARTICLE_SWOOSHES,
    /* 12 */ CART_ROOT_UNINDEXEDSET_DYNAMIC_LIGHTS,
    /* 13 */ CART_ROOT_UNINDEXEDSET_CURVES,
    /* 14 */ CART_ROOT_UNINDEXEDSET_RUMBLES,
    /* 15 */ CART_ROOT_UNINDEXEDSET_RUMBLE_TYPES,
    /* 16 */ CART_ROOT_INDEXEDSET_GRAPHICSET,
    /* 17 */ CART_ROOT_UNINDEXEDSET_GRAPHICSET_TYPE,
    /* 18 */ CART_ROOT_INDEXEDSET_CINEMAS,
    /* 19 */ CART_ROOT_UNINDEXEDSET_LINK_GROUP_TYPES
};

#endif

